project:
  type: website
  output-dir: docs

website:
  title: "Boris DevOps Lab"
  description: "Automatización • IA • Cloud • Pipelines • Bedrock → Lambda → API"
  site-url: "https://USERNAME.github.io/REPO"
  favicon: images/favicon.ico

  navbar:
    pinned: true
    background: "#0A1A2F"
    foreground: "white"

    left:
      - text: Home
        href: index.qmd
      - text: Blog
        href: posts/index.qmd
      - text: API Demo
        href: api-demo.qmd
      - text: Projects
        href: projects/index.qmd

    right:
      - icon: github
        href: https://github.com/USERNAME/REPO
      - icon: rss
        href: posts/index.xml

format:
  html:
    theme:
      light: cosmo
      dark: cyborg
    css: styles.css
    code-copy: true
    toc: true
    smooth-scroll: true

search: true

