project:
  type: website
  output-dir: docs

execute:
  enabled: false

website:
  title: "Bedrock-IA"
  site-url: "https://borizsam.github.io/quarto-bedrock"

  navbar:
    pinned: true
    left:
      - text: Blog
        href: posts/
      - text: API Demo
        href: api-demo.qmd
      - text: Workflow
        href: workflow.qmd
    right:
      - icon: github
        href: https://github.com/borizSam
        aria-label: GitHub
format:
  html:
    theme:
      light: cosmo
      dark: cyborg
    css: styles.css
    toc: false
